// A short in-app guide, condensed from the web app's Help page and rewritten for what the phone app actually offers.
export type HelpGuide = { id: string; title: string; steps: string[]; tips: string[] };

export const HELP_GUIDES: HelpGuide[] = [
  { id: "households", title: "Households", steps: ["Open More to see your households and tap one to switch - each keeps its own budget, calendar and notes.", "Notes, Meals, Calendar, Decisions and Documents follow you across all households you own."], tips: ["Running two currencies? That is what a second household is for. Create or remove households on the web app."] },
  { id: "budget", title: "Budget", steps: ["Add categories, then subcategories with a planned amount; set a due day on bill-like lines.", "Assign each transaction to a subcategory so Spent and Remaining update by themselves.", "Use the month arrows to move between months, and copy last month's budget into a new one."], tips: ["Income comes from your paychecks - add it in Paycheck/Income.", "Mark recurring bills so money is set aside every month."] },
  { id: "transactions", title: "Transactions and Bank stream", steps: ["Add a transaction by hand, or import a CSV/PDF statement into Bank stream.", "Review each imported row: pick a subcategory and account, then accept it, move it to Transfers, or dismiss it.", "Split a transaction across categories, or with friends (it creates IOUs)."], tips: ["Possible duplicate, refund and transfer badges flag likely re-imports before you accept them.", "No history for a payee? Use Suggest with AI."] },
  { id: "paychecks", title: "Paycheck/Income", steps: ["Add a paycheck with its repeat schedule and deposit account.", "Open its edit panel to change details, assign bills to it, or adjust an individual pay date."], tips: ["A pay date edited by hand keeps its amount when you change the paycheck's amount."] },
  { id: "calendar", title: "Calendar and Home", steps: ["Add chores, reminders, birthdays and anniversaries; give reminders a time to be notified.", "Mark things done on Home or in Calendar - jointly assigned items drop off once your part is done.", "Add a location to get a Directions link; filter by person with the chips."], tips: ["Take a photo of an invitation or flyer to create a reminder from it."] },
  { id: "notes", title: "Notes", steps: ["Create notes with labels, colors, checklists and photos; pin, archive or trash them (trash empties after 7 days).", "Share a note by email, a public link, or with another FamilyLoop login."], tips: ["Give a note a reminder date and it shows on Home when due."] },
  { id: "journal", title: "Journal and Plan", steps: ["Write a journal entry with mood, gratitude, tags and photos; ask for a gentle reflection on your day.", "Plan your day with timed tasks, and log what actually happened."], tips: ["Journal and Plan are private to you, even from people with full household access."] },
  { id: "documents", title: "Documents", steps: ["Upload files, organise them in folders, rename them or make a copy.", "Link a file to a note or to an asset/liability in Wealth, and set an expiry date to get a heads-up."], tips: ["Documents are shared across every household you own."] },
  { id: "decisions", title: "Decisions", steps: ["Add a question, list pros and cons together, attach files, then mark it decided (you can reopen it)."], tips: ["Decisions are shared across all your households."] },
  { id: "money", title: "Wealth, goals and shared expenses", steps: ["Track accounts, holdings, debts and net worth; record transfers between accounts.", "Savings goals can auto-contribute by rounding up purchases or setting aside a share of each paycheck.", "Split bills with friends, record debts, and settle up in Shared Expenses."], tips: ["Switch the net-worth display currency from the Wealth screen."] },
  { id: "meals", title: "Meals and recipes", steps: ["Save recipes, then plan a meal into each day and slot; see nutrition and an aisle-grouped grocery list.", "Post an estimated grocery cost straight to your Groceries budget line."], tips: ["Planning an occupied slot replaces what was there."] },
  { id: "sharing", title: "Sharing and profile", steps: ["The household owner can invite people, set Can edit or View only, revoke access, and choose shared areas in Sharing.", "Change your name or password in Profile."], tips: ["Invites to several households at once are sent from the web app."] }
];
